# Generated by Django 3.2.4 on 2021-07-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyPulicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profile_image', models.ImageField(default='academy.png', upload_to='academy_profile_image%Y%m%d')),
                ('video_link', models.CharField(max_length=50)),
                ('facility_image_1', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('facility_image_2', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('facility_image_3', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('facility_image_4', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('facility_image_5', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('tournaments', models.TextField(blank=True, help_text='tournaments attended by this academy')),
                ('awards', models.TextField(help_text='Enter each award on a new line')),
                ('benefited_players', models.TextField(blank=True, help_text='players who got contracts from this academy')),
                ('video_link_for_players', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitedPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('position_of_play', models.CharField(choices=[('GK', 'GK'), ('CB', 'CB'), ('MF', 'MF'), ('ST', 'ST')], max_length=2)),
                ('footbal_level', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPublicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
