# Generated by Django 3.2.4 on 2021-07-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermentorship',
            name='duration',
            field=models.CharField(choices=[('3 months', '3-months'), ('6 months', '6-months'), ('1 year', '1-year')], max_length=10),
        ),
    ]
