# Generated by Django 3.2.4 on 2021-07-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_playermentorship_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermentorship',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
