# Generated by Django 3.2.4 on 2021-07-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_second_name_playermentorship_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermentorship',
            name='footbal_level',
            field=models.CharField(choices=[('Amateur', 'Amateur'), ('Semi Pro', 'Semi Pro'), ('Professional', 'Professional')], max_length=12),
        ),
    ]
