# Generated by Django 3.2.4 on 2021-07-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_playermentorship_publicity_academy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermentorship',
            old_name='publicity_academy',
            new_name='publicity_category',
        ),
    ]
