# Generated by Django 3.2.4 on 2021-07-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210709_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='academypulicity',
            name='duration',
            field=models.CharField(choices=[('3 months', '3-months'), ('6 months', '6-months'), ('1 year', '1-year')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
