# Generated by Django 3.2.4 on 2021-07-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210711_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicitypayment',
            name='txref',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='publicitypayment',
            name='transaction',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
