# Generated by Django 3.2.4 on 2021-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210711_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicitypayment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
