# Generated by Django 3.2.4 on 2021-07-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_publicitypayment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academypulicity',
            name='publicity_category',
        ),
    ]
