# Generated by Django 3.2.4 on 2021-07-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_academypulicity_publicity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academypulicity',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='playermentorship',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
