# Generated by Django 3.2.4 on 2021-07-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20210711_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academypulicity',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
