# Generated by Django 3.2.4 on 2021-07-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_academypulicity_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academypulicity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
