# Generated by Django 3.2.4 on 2021-07-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_academypulicity_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academypulicity',
            name='awards',
            field=models.TextField(default='', help_text='Enter each award on a new line'),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='benefited_players',
            field=models.TextField(blank=True, default='', help_text='players who got contracts from this academy'),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='duration',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='facility_image_1',
            field=models.ImageField(default='facility.png', upload_to='academy_facilities%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='facility_image_2',
            field=models.ImageField(default='facility.png', upload_to='academy_facilities%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='facility_image_3',
            field=models.ImageField(default='facility.png', upload_to='academy_facilities%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='facility_image_4',
            field=models.ImageField(default='facility.png', upload_to='academy_facilities%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='facility_image_5',
            field=models.ImageField(default='facility.png', upload_to='academy_facilities%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='tournaments',
            field=models.TextField(blank=True, default='', help_text='tournaments attended by this academy'),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='video_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='video_link_for_players',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
