# Generated by Django 3.2.4 on 2021-07-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20210731_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academypulicity',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='academypulicity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
