# Generated by Django 3.2.4 on 2021-08-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_academypulicity_video_link_for_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='playermentorship',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
