# Generated by Django 3.2.4 on 2021-08-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20210804_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('registration_date', models.DateField(auto_now=True)),
                ('expiration_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Consultations',
        ),
        migrations.RenameField(
            model_name='playermentorship',
            old_name='footbal_level',
            new_name='football_level',
        ),
    ]
