# Generated by Django 3.2.4 on 2021-06-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profile_image', models.ImageField(default='academy.png', upload_to='academy_profile_image%Y%m%d')),
                ('video_link', models.CharField(max_length=50)),
                ('facility_image_1', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('facility_image_2', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('facility_image_3', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('facility_image_4', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('facility_image_5', models.ImageField(blank=True, default='facility.png', upload_to='academy_facilities%Y%m%d')),
                ('tournaments', models.TextField(blank=True, help_text='tournaments attended by this academy')),
                ('awards', models.TextField(help_text='Enter each award on a new line')),
                ('benefited_players', models.TextField(blank=True, help_text='players who got contracts from this academy')),
                ('video_link_for_players', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitedPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
