# Generated by Django 3.2.4 on 2021-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='previous_club_finish',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='previous_club_start',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
