# Generated by Django 3.2.4 on 2021-06-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fullname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(choices=[('left_foot', 'Left Foot'), ('right_foot', 'Right Foot')], default=('right_foot', 'Right Foot'), max_length=12),
        ),
    ]
