# Generated by Django 3.2.4 on 2021-06-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210603_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_club_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='previous_club_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='previous_club_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
