# Generated by Django 3.2.4 on 2021-07-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210709_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
