# Generated by Django 3.2.4 on 2021-07-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fullname',
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
