# Generated by Django 3.2.4 on 2021-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_player_video_clip_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='awards',
            field=models.TextField(blank=True, help_text='Enter new award on a new line'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_club',
            field=models.CharField(blank=True, default='N/A', help_text='current club name', max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='educational_qualification',
            field=models.CharField(blank=True, choices=[('SSCE', 'SSCE'), ('Bsc', 'Bsc'), ('OND', 'OND'), ('HND', 'HND'), ('Phd', 'Phd')], max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='hobbies',
            field=models.CharField(blank=True, help_text='seporate hobbies with a comma', max_length=600),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_position',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('left_foot', 'Left Foot'), ('right_foot', 'Right Foot')], default=('right_foot', 'Right Foot'), max_length=12),
        ),
        migrations.AlterField(
            model_name='player',
            name='previous_club',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='referees',
            field=models.TextField(blank=True, help_text='format: name - phone, each referee should be on a new line'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
